FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# Due to a recent update in the Create React App library, we will need to change how we start our containers.

# In the upcoming lecture, you'll need to add the -it flag to run the container in interactive mode:

# docker run -it -p 3000:3000 CONTAINER_ID