apiVersion: v1
kind: pod
metadata: 
    name: client-pod
    labels: 
        component: web
spec:
     containers:
        - name: client
          image: stephengrider/multi-client
          ports: 
            - containerPort: 3000
            