apiVersion: v1
kind: Pod
metadata: 
    name: client-pod
    labels: 
        component: web
spec:
     containers:
        - name: client
          image: stephengrider/multi-client
          ports: 
            - containerPort: 3000


# config file used to create object
# 1. StatefulSet 2. ReplicaController 3. Pod 4. Service

# Services

# 1. CLUSTERIP
# 2. NodePort - Expose a container to the outside world(only good for dev purposes)
# 3. LoadBalancer
# 4. Ingress

# labels-selector