apiVersion: v1
kind: Pod
metadata: 
    name: client-pod
    labels: 
        component: web
spec:
     containers:
        - name: client
          image: stephengrider/multi-client
          ports: 
            - containerPort: 3000


# config file used to create object
# 1. StatefulSet 2. ReplicaController 3. Pod 4. Service

# Services

# 1. CLUSTERIP
# 2. NodePort - Expose a container to the outside world(only good for dev purposes)
# 3. LoadBalancer
# 4. Ingress

# labels-selector

# SOME IMPORTANT POINTS
# 1. kubernetes is a system to deploy containerized apps
# 2. Nodes are individual machine that run containers.
# 3. Masters are machines with a set of program to manage Nodes
# 4. Kubernetes didn't build our images - it got them from somewhere else
# 5. Kubernetes (the master) decided to run each other - each nodecan run a dissimlar of containers. 
# 6. To deploy something we update the desired state of the master with a config file
# 7. The master work constantly to meet your desired state. 