version: '3'

services: 
    redis-server: 
        image: 'redis'

    node-app: 
        restart: on-failure
        build: .
        ports: 
            - "8081:8081"

# docker-compose up --build --> to rebuild the app. Otherwise you can remove the build part

# docker-compose up -d
# Starting visits_redis-server_1 ... done
# Starting visits_node-app_1     ... done

# TO stop
# docker-compose down

# Restart Policies
# 1. no - never attempt to restart this
# 2. always - Restart the container
# 3. on-failure - Only restart if the container stops with an error code
# 4. unless-stopped - Always restart unless (the developers) forciby stop it. 


