apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: hello
    image: siddhant777/hello:v1
    imagePullPolicy: IfNotPresent
  nodeName: worker2-control-plane

# skaffold build
# skaffold run
# skaffold run --tail
# skaffold dev 
# skaffold build -p cloud-build