apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: appname
        image: richardchesterwood/k8s-fleetman-queue:release1
        ports:
        - containerPort: 8080
