apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-queue:release1
        ports:
        - containerPort: 8080

---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: position-simulator
    spec:
      selector:
        matchLabels:
          app: position-simulator
      replicas: 1
      template:
        metadata:
          labels:
            app: position-simulator
        spec:
          containers:
          - name: webapp
            image: richardchesterwood/k8s-fleetman-position-simulator
            env: 
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice