version: '3'
services: 
    postgres: 
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgres
    redis:
        image: 'redis:latest'
    server: 
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
             - /app/node_modules
             - ./server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PG_USER=postgres
            - PG_HOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres
            - PGPORT=5432

